# Generated by Django 4.1.1 on 2022-09-28 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_category_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_publish',
            field=models.BooleanField(default=True),
        ),
    ]
